version: 2
updates:
    -
        package-ecosystem: "composer"
        directory: "/tools/php-7.4"
        schedule:
            interval: "daily"
    -
        package-ecosystem: "composer"
        directory: "/tools/php-8.1"
        schedule:
            interval: "daily"
    -
        package-ecosystem: "docker"
        directory: "/"
        schedule:
            interval: "daily"
    -
        package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "daily"
